import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Preset } from '../components/preset'
import { HeaderComponent } from '../components/header'


export default function Home() {
  return (
    <>
      <Head>
        <title>Easy Presets - Lightroom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <HeaderComponent />
      </div>
      <main className={styles.main}>

          <div>
            <Preset
              image={'dark'}
            />
          </div>

        {/* <div className={styles.center}>
          <Image
            className={styles.logo}
            src="https://github.com/BrunoKrugel/presets-info/blob/main/Before/Joker.jpg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div> */}
      </main>
    </>
  )
}
